### ISSUE TITLE
Add Search capability

### ISSUE THREAD

**Issue by gvenzl** [oracle-sql-features/oracle-sql-features.github.io#17]

**Comment by aalmiray** [comment]
Add the `lunr` extension to enable search https://gitlab.com/antora/antora-lunr-extension

A drawback of having multiple copies of the same category/version results in multiple hits for the same term. For example, at the moment "javascript" returns 4 hits that point to 4 different pages (paths) with the same content. There's no way to filter as technically these are 4 distinct pages that happen to get hit by the same search term.
