### ISSUE TITLE
"Edit this Page" should link to the actual source of feature page

### ISSUE THREAD

**Issue by gvenzl** [oracle-sql-features/oracle-sql-features.github.io#19]
The "Edit this Page" button does not link the user back to the feature page source but rather the generated page, e.g:

<img width="1027" alt="image" src="https://github.com/oracle-sql-features/oracle-sql-features.github.io/assets/4610293/be467409-05a3-468c-a940-266ded785eb3">

<img width="885" alt="image" src="https://github.com/oracle-sql-features/oracle-sql-features.github.io/assets/4610293/d74082ad-3915-42e9-a87e-b3c446c6ade3">

**Comment by aalmiray** [comment]
Looks like providing this behavior requires building a custom Antora extension based on the structure we have to keep 1 original copy of a given feature page, and multiple "copies" that include the feature page. https://antora.zulipchat.com/#narrow/stream/282400-users/topic/Customize.20edit_url

**Comment by aalmiray** [comment]
Editing index pages for categories & version yet to be done.
